osx_image: xcode8.1

os:
  - osx

before_script:
  - wget https://www.fusetools.com/downloads/latest/beta/osx -O fuse-installer.pkg &&
    sudo installer -pkg fuse-installer.pkg -target /

script:
  - uno build -tios --set:Project.iOS.DevelopmentTeam="HRA3AUNUHS"
  - cd build/iOS/Debug 
  - xcodebuild -project emrals.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO