osx_image: xcode8.1

os:
  - osx

before_script:
  - wget https://www.fusetools.com/downloads/latest/beta/osx -O fuse-installer.pkg &&
    sudo installer -pkg fuse-installer.pkg -target /

script:
  - uno build -tios Fuse/emrals.unoproj